/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cms.accountant;
import java.sql.*;
import cms.connectivity;
import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import java.time.*;
/**
 *
 * @author Dell
 */
public class paidfee extends javax.swing.JInternalFrame implements connectivity{

    /**
     * Creates new form paidfee
     */
    public paidfee() {
        initComponents();
        jLabel11.setVisible(false);
        jLabel16.setVisible(false);
        jLabel17.setVisible(false);
        jLabel18.setVisible(false);
        jLabel19.setVisible(false);
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setTitle("Paid Fees");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setText("Calculate Fees");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(384, 100, 110, -1));

        jButton1.setText(" Fetch Details");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(384, 63, 110, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Students Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel1.setEnabled(false);
        jPanel1.setFocusable(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Roll No");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Name");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 62, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Course");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 88, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Sem");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 40, 20));

        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 27, 132, -1));

        jTextField2.setEditable(false);
        jTextField2.setText("Paid Fees");
        jTextField2.setFocusable(false);
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 56, 132, -1));

        jTextField5.setEditable(false);
        jPanel1.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 85, 132, -1));

        jTextField6.setEditable(false);
        jPanel1.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 116, 132, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/mini_background.jpg"))); // NOI18N
        jLabel6.setText("jLabel6");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 160));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 40, 348, 160));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Fee");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 11, -1, -1));

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Late Fee");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 11, -1, -1));

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Addmission Fee");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 11, -1, -1));

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Examination Fee");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 11, -1, -1));

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Total Fee");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(373, 11, -1, -1));

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText(".....");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 43, -1, -1));

        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText(".....");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 43, -1, -1));

        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText(".....");
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 43, 74, -1));

        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("..... ");
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 43, 79, -1));

        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText(".....");
        jPanel3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(373, 43, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/mini_background.jpg"))); // NOI18N
        jLabel7.setText("jLabel7");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 120));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 460, 120));

        jButton3.setText("Print");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 370, -1, -1));

        jButton4.setText("Paid Fee");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/mini_background.jpg"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 400));

        setBounds(0, 0, 549, 431);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jLabel11.setVisible(true);
        jLabel16.setVisible(true);
        jLabel17.setVisible(true);
        jLabel18.setVisible(true);
        jLabel19.setVisible(true);
        jLabel11.setText(String.valueOf(0));
        jLabel16.setText(String.valueOf(0));
        jLabel17.setText(String.valueOf(0));
        jLabel18.setText(String.valueOf(0));
        jLabel19.setText(String.valueOf(0));
        
         
        try
        {

            Connection conn=DriverManager.getConnection(URL,USER,PASS);
            String q1="select * from fee where course=? and sem=?";
            PreparedStatement s1=conn.prepareStatement(q1);
            s1.setString(1,jTextField5.getText());
            s1.setString(2,jTextField6.getText());
            ResultSet rs=s1.executeQuery();
           if(rs.next())
            {
                float fee=rs.getFloat("fee");
                float exam_fee=rs.getFloat("exam_fee");
                float adm_fee=rs.getFloat("adm_fee");
                float ttl=fee+exam_fee+adm_fee;
              jLabel11.setText(String.valueOf(fee));
              jLabel17.setText(String.valueOf(adm_fee));
              jLabel18.setText(String.valueOf(exam_fee));
              jLabel19.setText(String.valueOf(ttl));
            
//              try
//              {
//              String q="insert into payments (roll_no,Name,course,sem,fee,late_fee,adm_fee,exam_fee,total_fee,date)values (?,?,?,?,?,?,?,?,?,?)";
//              PreparedStatement s=conn.prepareStatement(q);
//              s.setString(1,jTextField1.getText());
//              s.setString(2,jTextField2.getText());
//              s.setString(3,jTextField5.getText());
//              s.setString(4,jTextField6.getText());
//               s.setString(5, jLabel11.getText());
//               s.setString(6, jLabel16.getText());
//               s.setString(7, jLabel17.getText());
//               s.setString(8, jLabel18.getText());
//               s.setString(9, jLabel19.getText());
//               s.setString(10,myformat.format(date));
//                
//              int r=s.executeUpdate();
//              if(r==1)
//              {
//              JOptionPane.showMessageDialog(rootPane, "done");
//              
//              }
//              }
//              catch(Exception e)
//              {
//              JOptionPane.showMessageDialog(rootPane, "Error :"+e.getMessage());
//              }
            }
        }
        catch(Exception e)
        {

        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String roll=jTextField1.getText();
        try
        {
            Connection conn=DriverManager.getConnection(URL,USER,PASS);
           String q1="Select * from students where roll_no=?";
        PreparedStatement smt=conn.prepareStatement(q1);
        smt.setString(1,jTextField1.getText());
            ResultSet rs=smt.executeQuery();
            while(rs.next())
            {
               jTextField1.setText(rs.getString("roll_no"));
                jTextField2.setText(rs.getString("Stu_name"));
                jTextField5.setText(rs.getString("course"));
                jTextField6.setText(rs.getString("semm"));
            }
        }

        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,""+e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        feeslip obj=new feeslip();
        obj.setVisible(true);
        getParent().add(obj);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
       if(!(Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE|| c==KeyEvent.VK_DELETE || c==KeyEvent.VK_SPACE)))
        {
            evt.consume();
            //jLabel9.setForeground(Color.red);
            JOptionPane.showMessageDialog(null," Enter Only Digits (0-9) ");
        }
    }//GEN-LAST:event_jTextField1KeyTyped

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
                     
        SimpleDateFormat myformat = new SimpleDateFormat("yyyy-MM-dd");
         java.util.Date date=new java.util.Date();try
              {
                  Connection conn=DriverManager.getConnection(URL, USER, PASS);
              String q="insert into payments (roll_no,Name,course,sem,fee,late_fee,adm_fee,exam_fee,total_fee,date)values (?,?,?,?,?,?,?,?,?,?)";
              PreparedStatement s=conn.prepareStatement(q);
              s.setString(1,jTextField1.getText());
              s.setString(2,jTextField2.getText());
              s.setString(3,jTextField5.getText());
              s.setString(4,jTextField6.getText());
               s.setString(5, jLabel11.getText());
               s.setString(6, jLabel16.getText());
               s.setString(7, jLabel17.getText());
               s.setString(8, jLabel18.getText());
               s.setString(9, jLabel19.getText());
               s.setString(10,myformat.format(date));
                
              int r=s.executeUpdate();
              if(r==1)
              {
              JOptionPane.showMessageDialog(rootPane, "Fees Paid by "+jTextField2.getText().toUpperCase()+" ");
              
              }
              }
              catch(Exception e)
              {
              JOptionPane.showMessageDialog(rootPane, "Error :"+e.getMessage());
              }
    }//GEN-LAST:event_jButton4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
