/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cms.acedmic;
import cms.connectivity;
import java.awt.event.KeyEvent;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
/**
 *
 * @author Dell
 */
public class addmarks extends javax.swing.JInternalFrame implements connectivity{

    /**
     * Creates new form adddmarks
     */
    public addmarks() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jComboBox8 = new javax.swing.JComboBox<>();
        jComboBox9 = new javax.swing.JComboBox<>();
        jTextField9 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jComboBox10 = new javax.swing.JComboBox<>();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jFormattedTextField4 = new javax.swing.JFormattedTextField();
        jFormattedTextField5 = new javax.swing.JFormattedTextField();
        jFormattedTextField6 = new javax.swing.JFormattedTextField();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setTitle("Marks Submit");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Course ");
        jPanel7.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 11, 61, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText(" Semester");
        jPanel7.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 52, -1, 25));

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Roll No");
        jPanel7.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(292, 12, -1, -1));

        jComboBox8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose Your Course", "BCA", "BBA", "B.COM", "M.COM", "MCA", "MBA" }));
        jComboBox8.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox8ItemStateChanged(evt);
            }
        });
        jComboBox8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox8ActionPerformed(evt);
            }
        });
        jPanel7.add(jComboBox8, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 11, 144, -1));

        jComboBox9.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose your Semester", "1", "2", "3", "4", "5", "6", "7", "8" }));
        jComboBox9.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox9ItemStateChanged(evt);
            }
        });
        jComboBox9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox9jComboBox2ActionPerformed(evt);
            }
        });
        jPanel7.add(jComboBox9, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 150, -1));

        jTextField9.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField9KeyTyped(evt);
            }
        });
        jPanel7.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(344, 12, 109, -1));

        jButton4.setText("Fetch Data");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4jButton1ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(487, 11, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/mini_background.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel7.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 110));

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Student Name");
        jPanel8.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("F. Name");
        jPanel8.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 49, -1, -1));

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("M. Name");
        jPanel8.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 87, -1, -1));

        jTextField10.setEditable(false);
        jPanel8.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 11, 176, -1));

        jTextField11.setEditable(false);
        jPanel8.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 49, 173, -1));

        jTextField12.setEditable(false);
        jPanel8.add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 87, 173, -1));

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Course");
        jPanel8.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 11, -1, -1));

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Semester");
        jPanel8.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 49, -1, -1));

        jTextField13.setEditable(false);
        jPanel8.add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 11, 147, -1));

        jTextField14.setEditable(false);
        jPanel8.add(jTextField14, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 49, 147, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/mini_background.jpg"))); // NOI18N
        jLabel3.setText("jLabel2");
        jPanel8.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 130));

        getContentPane().add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 117, -1, -1));

        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBox10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jComboBox10.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Subject" }));
        jComboBox10.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox10ItemStateChanged(evt);
            }
        });
        jComboBox10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox10MouseClicked(evt);
            }
        });
        jPanel9.add(jComboBox10, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 11, 152, -1));

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Subject");
        jPanel9.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 12, -1, -1));

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Total Marks");
        jPanel9.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 54, -1, -1));

        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("Marks Obtained");
        jPanel9.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 54, -1, -1));

        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("Min Marks");
        jPanel9.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 54, -1, -1));

        jFormattedTextField4.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,###.00"))));
        jFormattedTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jFormattedTextField4KeyTyped(evt);
            }
        });
        jPanel9.add(jFormattedTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 52, 82, -1));

        jFormattedTextField5.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        jFormattedTextField5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jFormattedTextField5KeyTyped(evt);
            }
        });
        jPanel9.add(jFormattedTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 52, 81, -1));

        jFormattedTextField6.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        jFormattedTextField6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jFormattedTextField6KeyTyped(evt);
            }
        });
        jPanel9.add(jFormattedTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(514, 52, 81, -1));

        jButton3.setText("ADD Marks");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(514, 11, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Sub Code");
        jPanel9.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(278, 14, -1, -1));

        jTextField2.setEditable(false);
        jPanel9.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 14, 97, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/mini_background.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel9.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -6, 640, 120));

        getContentPane().add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 246, 610, 100));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Subject Code", "Subject Name", "Max Marks", "Min Mark", "Marks Obtained"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(664, 11, 430, 343));

        jButton5.setText("Submit");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 365, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/mini_background.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 4, 1130, 410));

        setBounds(0, 0, 1146, 447);
    }// </editor-fold>//GEN-END:initComponents
boolean fetch_valid()
{
 if(jTextField9.getText().isEmpty()||jTextField9.getText().length()<2)
 {
 JOptionPane.showMessageDialog(rootPane, "Enter a Roll no ");
 return(false);
 }
 else if(jComboBox8.getSelectedItem()=="Choose Your Course")
 {
 JOptionPane.showMessageDialog(rootPane, "Choose Your Course");
 return(false);
 }
 else if(jComboBox9.getSelectedItem()=="Choose your Semester")
 {
 JOptionPane.showMessageDialog(rootPane, "Choose your Semester");
 return(false);
 }
 else
 {
 return(true);
 }
}
    private void jComboBox9jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox9jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox9jComboBox2ActionPerformed

    private void jButton4jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4jButton1ActionPerformed
        // TODO add your handling code here:
      if(fetch_valid()==true)
      {
          try
        {
          Connection conn=DriverManager.getConnection(URL, USER, PASS);
          String q1="select * from subjects where Course=? and Semester=? ";
          String q2="select * from students where roll_no =?";
          PreparedStatement smt1=conn.prepareStatement(q1);
          PreparedStatement smt2=conn.prepareStatement(q2);
          smt1.setString(1,jComboBox8.getSelectedItem().toString());
          smt1.setString(2,jComboBox9.getSelectedItem().toString());
          smt2.setString(1, jTextField9.getText());
          ResultSet rs1=smt1.executeQuery();
          ResultSet rs2=smt2.executeQuery();
//          jComboBox10.removeAllItems();
          if(rs1.next())
            {
//              jComboBox10.removeAllItems();
             do
                {
                    jComboBox10.addItem(rs1.getString("subname"));
                }while(rs1.next());
             }
          
          if(rs2.next())
          {
          jTextField10.setText(rs2.getString("Stu_name"));
          jTextField11.setText(rs2.getString("F_name"));
          jTextField12.setText(rs2.getString("M_name"));
          jTextField13.setText(rs2.getString("course"));
          jTextField14.setText(rs2.getString("semm"));
          }
        }
        catch(Exception e)
        {
        JOptionPane.showMessageDialog(rootPane, " Error : "+e.getMessage());
        }
      }
    }//GEN-LAST:event_jButton4jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
      DefaultTableModel my=(DefaultTableModel)jTable1.getModel();
        String sub=jComboBox10.getSelectedItem().toString().toUpperCase();
        String code=jTextField2.getText().toUpperCase();
        Float ttl_m=Float.parseFloat(jFormattedTextField4.getText().toUpperCase());
         Float min_m=Float.parseFloat(jFormattedTextField5.getText().toUpperCase());
          Float obt_m=Float.parseFloat(jFormattedTextField6.getText().toUpperCase());
        Object obj[]={code,sub,ttl_m,min_m,obt_m};
        my.addRow(obj);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jComboBox10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox10MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox10MouseClicked

    private void jComboBox10ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox10ItemStateChanged
        // TODO add your handling code here:
         String sub=jComboBox10.getSelectedItem().toString();
        try
        {
            Connection conn=DriverManager.getConnection(URL, USER, PASS);
            String q1="select * from subjects where subname=?";
            PreparedStatement smt=conn.prepareStatement(q1);
            smt.setString(1,sub);
            ResultSet rs=smt.executeQuery();
            if(rs.next())
            {
                jTextField2.setText(rs.getString("subcode"));
                jFormattedTextField4.setText(rs.getString("Max_mark"));
                jFormattedTextField5.setText(null);
                jFormattedTextField6.setText(null);
            }
        }
        catch(Exception e)
        {
        JOptionPane.showMessageDialog(rootPane, " Error : "+e.getMessage());
        }
    }//GEN-LAST:event_jComboBox10ItemStateChanged

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        try
        {
        Connection conn=DriverManager.getConnection(URL, USER, PASS);
        
        for(int i=0;i<jTable1.getRowCount();i++)
        {
            
              String q1="insert into marks values (?,?,?,?,?,?,?,?,?)";
        PreparedStatement smt=conn.prepareStatement(q1);
//        for(int i=0;i<jTable1.getRowCount();i++)
            
                smt.setString(1, jTextField9.getText());
                smt.setString(2, jTextField10.getText());
                smt.setString(3, String.valueOf(jTable1.getValueAt(i, 0)));
                smt.setString(4, String.valueOf( jTable1.getValueAt(i, 1)));
                smt.setFloat(5, (float) jTable1.getValueAt(i, 2));
                smt.setFloat(6, (float) jTable1.getValueAt(i, 3));
                smt.setFloat(7, (float) jTable1.getValueAt(i, 4));
                smt.setString(8,jComboBox8.getSelectedItem().toString());
                smt.setString(9,jComboBox9.getSelectedItem().toString());
            
            
        int rs=smt.executeUpdate();
        if(rs==1)
            {
                jComboBox10.removeAll();
                JOptionPane.showMessageDialog(rootPane, " Final Submitted ...");
//            
        }
            }
        
        }
        catch(Exception e)
        {
        JOptionPane.showMessageDialog(rootPane, " Error : "+e.getMessage());
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTextField9KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField9KeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(!(Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE|| c==KeyEvent.VK_DELETE || c==KeyEvent.VK_SPACE )))
        {
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, " Enter only Digits (0-9) ");
        }
    }//GEN-LAST:event_jTextField9KeyTyped

    private void jFormattedTextField4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFormattedTextField4KeyTyped
        // TODO add your handling code here:
         char c=evt.getKeyChar();
            if(!(Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE|| c==KeyEvent.VK_DELETE || c==KeyEvent.VK_SPACE )))
       {
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, " Enter only Digits (0-9) ");
        }
    }//GEN-LAST:event_jFormattedTextField4KeyTyped

    private void jFormattedTextField5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFormattedTextField5KeyTyped
        // TODO add your handling code here:
         char c=evt.getKeyChar();
        if(!(Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE|| c==KeyEvent.VK_DELETE || c==KeyEvent.VK_SPACE )))
        {
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, " Enter only Digits (0-9) ");
        }
    }//GEN-LAST:event_jFormattedTextField5KeyTyped

    private void jFormattedTextField6KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFormattedTextField6KeyTyped
        // TODO add your handling code here:
         char c=evt.getKeyChar();
        if(!(Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE|| c==KeyEvent.VK_DELETE || c==KeyEvent.VK_SPACE )))
       {
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, " Enter only Digits (0-9) ");
        }
    }//GEN-LAST:event_jFormattedTextField6KeyTyped

    private void jComboBox9ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox9ItemStateChanged
        // TODO add your handling code here:
        jComboBox10.removeAllItems();
    }//GEN-LAST:event_jComboBox9ItemStateChanged

    private void jComboBox8ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox8ItemStateChanged
        // TODO add your handling code here:
        jComboBox10.removeAllItems();
    }//GEN-LAST:event_jComboBox8ItemStateChanged

    private void jComboBox8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox8ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox10;
    private javax.swing.JComboBox<String> jComboBox8;
    private javax.swing.JComboBox<String> jComboBox9;
    private javax.swing.JFormattedTextField jFormattedTextField4;
    private javax.swing.JFormattedTextField jFormattedTextField5;
    private javax.swing.JFormattedTextField jFormattedTextField6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
