/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cms.user;
import cms.Library.*;
import static java.awt.Frame.MAXIMIZED_BOTH;
import java.sql.*;
import cms.*;
import static cms.connectivity.PASS;
import static cms.connectivity.URL;
import static cms.connectivity.USER;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
/**
 *
 * @author Singh
 */
public class stu extends javax.swing.JInternalFrame implements connectivity{

    /**
     * Creates new form stu_signup
     */
    public stu() {
        initComponents();
        this.setLocation(250, 20);
    }
void clear()
{
jTextField1.setText(null);
jTextField2.setText(null);
jTextField3.setText(null);
jTextField5.setText(null);
jTextField4.setText(null);
jFormattedTextField1.setText(null);
jPasswordField1.setText(null);
jComboBox1.setSelectedIndex(0);
jComboBox2.setSelectedIndex(0);
jDateChooser1.setCalendar(null);
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel13 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jOptionPane1 = new javax.swing.JOptionPane();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jButton2 = new javax.swing.JButton();
        jTextField4 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setTitle("Student Manage");
        setToolTipText("Student Manage");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Father Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Mother Name");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Contact No");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, -1, -1));

        jButton1.setText("Update");
        jButton1.setEnabled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 510, -1, -1));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 185, -1));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 185, -1));
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 185, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Student ID");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, -1, -1));

        jButton3.setText("Search");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 70, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Student Name ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, -1, -1));

        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 185, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Password");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, -1, -1));

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Course"));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Select Course");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 30, -1, -1));

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select your Course", "BCA", "B.COM", "BBA", "MCA", "MBA", "M.COM" }));
        jPanel3.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 27, 182, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Semester");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 69, -1, -1));

        jComboBox2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Your Semester", "1", "2", "3", "4", "5", "6" }));
        jPanel3.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 66, 182, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Roll No.");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 107, -1, -1));
        jPanel3.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 105, 95, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/mini_background.jpg"))); // NOI18N
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 160));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Manage Student");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 229, -1));
        getContentPane().add(jOptionPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 150, 0, 28));
        getContentPane().add(jFormattedTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, 180, -1));

        jButton2.setText("Delete ");
        jButton2.setEnabled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 510, -1, -1));
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 180, -1));

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("DOB");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, 80, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Contact No");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, -1, -1));
        getContentPane().add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, 180, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/mini_background.jpg"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 590));

        setBounds(0, 0, 579, 603);
    }// </editor-fold>//GEN-END:initComponents
 String pre_id;
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String name=jTextField1.getText();
        String F_name=jTextField2.getText();
        String M_name=jTextField3.getText();
        String Contact=jFormattedTextField1.getText();
        String password=jPasswordField1.getText();
        String Course=(String)jComboBox1.getSelectedItem();
        String semm=(String)jComboBox2.getSelectedItem();
        String roll_no=jTextField5.getText();
        String stu_id=jTextField4.getText();
            
        if(name.isEmpty()||F_name.isEmpty()||M_name.isEmpty()||Contact.isEmpty()||password.isEmpty()||roll_no.isEmpty()||stu_id.isEmpty()||Course.equalsIgnoreCase("select your course")||semm.equalsIgnoreCase("select your semester"))
            {
            jOptionPane1.showMessageDialog(null," Enter a All Fields ");
               if(Course.equalsIgnoreCase("select your course"))
            {
                jOptionPane1.showMessageDialog(null,"Please choose Course");
            }
               if(semm.equalsIgnoreCase("select your semester"))
            {
                jOptionPane1.showMessageDialog(null,"Please choose Semester");
            }
            }
            else
            {
             
            try{
                
                Connection conn=DriverManager.getConnection(URL,USER,PASS);
                String s1="update students set Stu_name=?,password=?,F_name=?,M_name=?,contact=?,course=?,semm=?,roll_no=?,stu_id=?,dob=? where stu_id=?";
                PreparedStatement smt=conn.prepareStatement(s1);
                smt.setString(1,jTextField1.getText());
                smt.setString(2, jPasswordField1.getText());
                smt.setString(3, jTextField2.getText());
                smt.setString(4, jTextField3.getText());
                smt.setString(5, jFormattedTextField1.getText());
                smt.setString(6, jComboBox1.getSelectedItem().toString());
                smt.setString(7, jComboBox2.getSelectedItem().toString());
                smt.setString(8, jTextField5.getText());
                smt.setString(9, jTextField4.getText());
                SimpleDateFormat myformat = new SimpleDateFormat("yyyy-MM-dd");
                String dob = myformat.format(jDateChooser1.getDate());
                smt.setString(10,dob);
                smt.setString(11,pre_id);
                int rs=smt.executeUpdate();
                if(rs==1)
                {
                jOptionPane1.showMessageDialog(this,"Signup Successfully");
                clear();
                }
            }
            catch(Exception e)
            {
                jOptionPane1.showMessageDialog(this,e.getMessage());
            }
            
            }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try
        {
            Connection conn=DriverManager.getConnection(URL,USER,PASS); 
            String q1="select * from students where stu_id=?";
            PreparedStatement s1=conn.prepareStatement(q1);
            s1.setString(1, jTextField4.getText());
            ResultSet rs=s1.executeQuery();
            if(rs.next())
            {
                String pre_id=rs.getString("stu_id");
                jButton2.setEnabled(true);
                jButton1.setEnabled(true);
              jTextField1.setText(rs.getString("stu_name").toUpperCase());
              jPasswordField1.setText(rs.getString("password").toUpperCase());
              jTextField2.setText(rs.getString("f_name").toUpperCase());
              jTextField3.setText(rs.getString("m_name").toUpperCase());
              jFormattedTextField1.setText(rs.getString("contact").toUpperCase());
              jComboBox1.setSelectedItem(rs.getString("course").toUpperCase());
              jComboBox2.setSelectedItem(rs.getString("semm").toUpperCase());
              jTextField5.setText(rs.getString("roll_no").toUpperCase());
            }
            else
            {
                jOptionPane1.showMessageDialog(null," You Select This User Id ");
            }
        }
        catch(Exception e)
        {
             jOptionPane1.showMessageDialog(this,"Error : "+e.getMessage());
        }
       
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int ch=JOptionPane.showConfirmDialog(rootPane, "Do You Want to Delete Student ?", "Delete Student Confirmation Message ",0,1);
    if(ch==JOptionPane.YES_OPTION)
    {
    try
      {
       Connection conn=DriverManager.getConnection(URL, USER, PASS);
       String q1="delete from students where stu_id=?";
       PreparedStatement smt=conn.prepareStatement(q1);
       smt.setString(1,jTextField4.getText());
       int rs=smt.executeUpdate();
            if(rs==1)
            {
                JOptionPane.showMessageDialog(rootPane, "Student Deleted Successfully ....");
             
            }
       }  
         catch(Exception e)
       {
       JOptionPane.showMessageDialog(rootPane, "Error : "+e.getMessage());
       }  
    }
        
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
