/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cms.user;

import java.sql.*;
import cms.connectivity;
import java.text.SimpleDateFormat;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Dell
 */
public class view_user extends javax.swing.JInternalFrame implements connectivity{

    /**
     * Creates new form view_user
     */
    public view_user() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setTitle("View User's");

        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        jPanel1.setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Admin Id", "Admin Name", "Date Of Birth", "Password", "Type"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 80, 701, 299);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Admins");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(270, 30, 224, 34);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/mini_background.jpg"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(0, 0, 740, 420);

        jTabbedPane1.addTab("Admins", jPanel1);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Roll No", "Student ID", "Name", "Password", "Course", "Semester"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 701, 299));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Students");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, 224, 34));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/mini_background.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 400));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 721, 400));

        jTabbedPane1.addTab("Students", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 736, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 443, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
void admin()
{
    DefaultTableModel my= (DefaultTableModel)jTable1.getModel();
    try
        {
        Connection conn=DriverManager.getConnection(URL, USER, PASS);
        String s1="select * from admins";
        PreparedStatement smt=conn.prepareStatement(s1);
        ResultSet rs=smt.executeQuery();
        while(rs.next())
        {
        String id=rs.getString("adm_id");
        String name=rs.getString("name");
        String dob=rs.getString("dob");
        String pass=rs.getString("password");
        String type=rs.getString("type");
        Object obj[]={id,name,dob,pass,type};
        my.addRow(obj);
        }
        }
        catch(Exception e)
        {
        
        }
}

void student()
{

    DefaultTableModel my2= (DefaultTableModel)jTable2.getModel();
    try
        {
        Connection conn=DriverManager.getConnection(URL, USER, PASS);
        String s2="select * from students";
        PreparedStatement smt2=conn.prepareStatement(s2);
        ResultSet rs2=smt2.executeQuery();
       while(rs2.next())
        {
//            do
//            {
                String id=rs2.getString("stu_id");
                String name=rs2.getString("stu_name");
                String dob=rs2.getString("dob");
                String pass=rs2.getString("password");
                String course=rs2.getString("course");
                String semm=rs2.getString("semm");
                String roll=rs2.getString("roll_no");
                Object obj[]={roll,id,name,dob,pass,course,semm};
                my2.addRow(obj);
//            }while(rs2.next());
          }
        }
        catch(Exception e)
        {
        
        }


}
    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
        // TODO add your handling code here:
         DefaultTableModel my= (DefaultTableModel)jTable2.getModel();
         DefaultTableModel my1= (DefaultTableModel)jTable1.getModel();
         my.setRowCount(0);
         my1.setRowCount(0);
        admin();
        
    try
        {
        Connection conn=DriverManager.getConnection(URL, USER, PASS);
        String s2="select * from students order by roll_no";
        PreparedStatement smt2=conn.prepareStatement(s2);
        ResultSet rs2=smt2.executeQuery();
      while(rs2.next())
        {
          
                String id=rs2.getString("stu_id");
                String roll=rs2.getString("roll_no");
                String name=rs2.getString("Stu_name");                
                String pass=rs2.getString("password");
                String course=rs2.getString("course");
                String semm=rs2.getString("semm");
                
                Object obj[]={roll,id,name,pass,course,semm};
                my.addRow(obj);
            
          }
        }
        catch(Exception e)
        {
        
        }


    }//GEN-LAST:event_jTabbedPane1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
